module.exports = {
  apps: [{
    name: 'bluefish-sports-platform',
    script: 'src/app.js',
    instances: 1,
    exec_mode: 'fork',
    env: {
      NODE_ENV: 'production',
      PORT: 5001,
      DB_HOST: 'your-db-host',
      DB_PORT: 5432,
      DB_NAME: 'your-db-name',
      DB_USER: 'your-db-user',
      DB_PASSWORD: 'your-db-password',
      NBA_DB_HOST: 'your-nba-db-host',
      NBA_DB_PORT: 5432,
      NBA_DB_NAME: 'your-nba-db-name',
      NBA_DB_USER: 'your-nba-db-user',
      NBA_DB_PASSWORD: 'your-nba-db-password',
      TENNIS_DB_HOST: 'your-tennis-db-host',
      TENNIS_DB_PORT: 5432,
      TENNIS_DB_NAME: 'your-tennis-db-name',
      TENNIS_DB_USER: 'your-tennis-db-user',
      TENNIS_DB_PASSWORD: 'your-tennis-db-password',
      GOLF_DB_HOST: 'your-golf-db-host',
      GOLF_DB_PORT: 5432,
      GOLF_DB_NAME: 'your-golf-db-name',
      GOLF_DB_USER: 'your-golf-db-user',
      GOLF_DB_PASSWORD: 'your-golf-db-password',
      JWT_SECRET: 'your-jwt-secret',
      JWT_EXPIRES_IN: '24h',
      AWS_REGION: 'your-aws-region',
      AWS_ACCESS_KEY_ID: 'your-aws-access-key',
      AWS_SECRET_ACCESS_KEY: 'your-aws-secret-key',
      SES_FROM_EMAIL: 'your-email@example.com',
      FRONTEND_URL: 'https://yourdomain.com',
    },
    error_file: 'logs/err.log',
    out_file: 'logs/out.log',
    log_file: 'logs/combined.log',
    time: true,
    merge_logs: true,
    max_memory_restart: '1G',
    watch: false,
    autorestart: true
  }]
}; 